# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dataservice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dataservice.proto',
  package='protobufs',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x64\x61taservice.proto\x12\tprotobufs\"\"\n\rParamsRequest\x12\x11\n\ttest_size\x18\x01 \x01(\x02\"\x86\x01\n\x15\x42ostonHousingResponse\x12\x14\n\x0cnorm_train_x\x18\x01 \x01(\x0c\x12\x13\n\x0bnorm_test_x\x18\x02 \x01(\x0c\x12\x12\n\nnorm_val_x\x18\x03 \x01(\x0c\x12\x0f\n\x07train_y\x18\x04 \x01(\x0c\x12\x0e\n\x06test_y\x18\x05 \x01(\x0c\x12\r\n\x05val_y\x18\x06 \x01(\x0c\x32Z\n\rBostonHousing\x12I\n\x0bPrepareData\x12\x18.protobufs.ParamsRequest\x1a .protobufs.BostonHousingResponseb\x06proto3'
)




_PARAMSREQUEST = _descriptor.Descriptor(
  name='ParamsRequest',
  full_name='protobufs.ParamsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='test_size', full_name='protobufs.ParamsRequest.test_size', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=66,
)


_BOSTONHOUSINGRESPONSE = _descriptor.Descriptor(
  name='BostonHousingResponse',
  full_name='protobufs.BostonHousingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='norm_train_x', full_name='protobufs.BostonHousingResponse.norm_train_x', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='norm_test_x', full_name='protobufs.BostonHousingResponse.norm_test_x', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='norm_val_x', full_name='protobufs.BostonHousingResponse.norm_val_x', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='train_y', full_name='protobufs.BostonHousingResponse.train_y', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='test_y', full_name='protobufs.BostonHousingResponse.test_y', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='val_y', full_name='protobufs.BostonHousingResponse.val_y', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=203,
)

DESCRIPTOR.message_types_by_name['ParamsRequest'] = _PARAMSREQUEST
DESCRIPTOR.message_types_by_name['BostonHousingResponse'] = _BOSTONHOUSINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParamsRequest = _reflection.GeneratedProtocolMessageType('ParamsRequest', (_message.Message,), {
  'DESCRIPTOR' : _PARAMSREQUEST,
  '__module__' : 'dataservice_pb2'
  # @@protoc_insertion_point(class_scope:protobufs.ParamsRequest)
  })
_sym_db.RegisterMessage(ParamsRequest)

BostonHousingResponse = _reflection.GeneratedProtocolMessageType('BostonHousingResponse', (_message.Message,), {
  'DESCRIPTOR' : _BOSTONHOUSINGRESPONSE,
  '__module__' : 'dataservice_pb2'
  # @@protoc_insertion_point(class_scope:protobufs.BostonHousingResponse)
  })
_sym_db.RegisterMessage(BostonHousingResponse)



_BOSTONHOUSING = _descriptor.ServiceDescriptor(
  name='BostonHousing',
  full_name='protobufs.BostonHousing',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=205,
  serialized_end=295,
  methods=[
  _descriptor.MethodDescriptor(
    name='PrepareData',
    full_name='protobufs.BostonHousing.PrepareData',
    index=0,
    containing_service=None,
    input_type=_PARAMSREQUEST,
    output_type=_BOSTONHOUSINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BOSTONHOUSING)

DESCRIPTOR.services_by_name['BostonHousing'] = _BOSTONHOUSING

# @@protoc_insertion_point(module_scope)
